name: Run Tests

on:
  push:
    branches:
      - master  # Change this to the default branch of your repository
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if you have a different requirements file

    - name: Run tests
      run: |
        pytest  # Adjust this command if you are using a different test framework
